### ISSUE TITLE
LAMMPS doesn't read *.yace format

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/lammps-user-pace#6]
Hi,

Looks like lammps doesn't understand the YACE format. I'm getting the following error:

  what():  File 'output_potential.yace': couldn't read 'nelements'. Expected format: 'nelements=[number]'

This is how the header of my potential.yace file looks like:

elements: [Be, F, Li]
E0: [0, 0, 0]
deltaSplineBins: 0.001

**Comment by yury-lysogorskiy** [comment]
You should use recent version (after Oct 2021) of LAMMPS
