### ISSUE TITLE
Use of non-standard variable length arrays 

### ISSUE THREAD

**Issue by akohlmey** [ICAMS/lammps-user-pace#8]
Sorry, for coming back with some Windows related issue after having just close the previous one.

I am looking for ways to replace the cross-compiled LAMMPS Windows binaries with binaries that are compiled natively on Windows with the Microsoft Visual C++ compilers. This puts up some new hurdles.

One of them is that variable length arrays are not supported. Strictly speaking they are not supported in C++ at all (they are a C99 and a Fortran feature and the C standards people very much regret that they accepted them), but the GNU and Clang compilers accept them in the default "forgiving C++" mode too. According to the C++ standard any static array definition of:
`type array[size];`
is only allowed if "size" is a compile time constant, i.e. defined as `constexpr int size=<size>;`

However, the pace library makes some use of that (it *is* convenient) when the size arguments are not constant and thus there are errors with the MSVC++ compilers. You should be able to see those uses when compiling with GCC while adding  -Wvla.

Long-term goal is to have the pace pair style compiled as a plugin for LAMMPS so it can be distributed as a binary, especially on Windows without being linked into the LAMMPS executable, and to do this with the Microsoft Compilers and using the Microsoft maintained MSMPI library.

**Comment by yury-lysogorskiy** [comment]
@akohlmey Sorry for the veery delayed response, I fixed variable length arrays issue in  commit c344dbb298a9e1c7d48b3e4b9011f0e8567547da  that was part of PR #18
